### ISSUE TITLE
"TypeError: Cannot read property 'replace' of undefined" when including packages under plugins/support for cypress

### ISSUE THREAD

**Issue by azaeng04** [jscutlery/test-utils#41]
Following the instructions of just including the plugin seems to throw this stack trace error:

```
TypeError: Cannot read property 'replace' of undefined
    at Object.forwardSlashPath (/Users/azaeng04/projects/voss-portal/node_modules/@ngtools/webpack/src/utils.js:28:17)
    at AngularCompilerPlugin._setupOptions (/Users/azaeng04/projects/voss-portal/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:90:38)
    at new AngularCompilerPlugin (/Users/azaeng04/projects/voss-portal/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:66:14)
    at /Users/azaeng04/projects/voss-portal/packages/cypress-angular-preprocessor/src/lib/angular-preprocessor.ts:57:9
    at Generator.next (<anonymous>)
    at /Users/azaeng04/projects/voss-portal/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/azaeng04/projects/voss-portal/node_modules/tslib/tslib.js:113:16)
    at Object.handler (/Users/azaeng04/projects/voss-portal/packages/cypress-angular-preprocessor/src/lib/angular-preprocessor.ts:30:44)
    at invoke (/Users/azaeng04/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:22:16)
    at /Users/azaeng04/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:41:14
    at tryCatcher (/Users/azaeng04/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/azaeng04/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/azaeng04/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:40:23)
    at Object.wrap (/Users/azaeng04/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/preprocessor.js:28:8)
    at execute (/Users/azaeng04/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:119:27)
    at EventEmitter.<anonymous> (/Users/azaeng04/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:202:5)
    at EventEmitter.emit (events.js:315:20)
    at process.<anonymous> (/Users/azaeng04/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:315:20)
    at process.emit (/Users/azaeng04/Library/Caches/Cypress/6.9.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:876:12)
```

**Comment by Sathish787** [comment]
I am too getting same issue. Followed instructions as given here. 
```

TypeError: Cannot read property 'replace' of undefined
```
    at AngularCompilerPlugin._setupOptions (C:\Users\smunirathinam\Development\ptek-reporting-ui\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:203:47)
    at new AngularCompilerPlugin (C:\Users\smunirathinam\Development\ptek-reporting-ui\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:168:10)
    at C:\Users\smunirathinam\Development\ptek-reporting-ui\packages\cypress-angular-preprocessor\src\lib\angular-preprocessor.ts:57:9
    at Generator.next (<anonymous>)
    at C:\Users\smunirathinam\Development\ptek-reporting-ui\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\smunirathinam\Development\ptek-reporting-ui\node_modules\tslib\tslib.js:111:16)
    at Object.handler (C:\Users\smunirathinam\Development\ptek-reporting-ui\packages\cypress-angular-preprocessor\src\lib\angular-preprocessor.ts:30:44)
    at invoke (C:\Users\smunirathinam\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:22:16)
    at C:\Users\smunirathinam\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\plugins\util.js:41:14
    at tryCatcher (C:\Users\smunirathinam\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\smunirathinam\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\method.js:39:29)
    at Object.wrapChildPromise (C:\Users\smunirathinam\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\plugins\util.js:40:23)
    at Object.wrap (C:\Users\smunirathinam\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\plugins\child\preprocessor.js:28:8)
    at execute (C:\Users\smunirathinam\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:119:27)
    at EventEmitter.<anonymous> (C:\Users\smunirathinam\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:202:5)
    at EventEmitter.emit (events.js:315:20)
    at process.<anonymous> (C:\Users\smunirathinam\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at process.emit (events.js:315:20)
    at process.emit (C:\Users\smunirathinam\AppData\Local\Cypress\Cache\6.8.0\Cypress\resources\app\packages\server\node_modules\source-map-support\source-map-support.js:495:21)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```
```

**Comment by azaeng04** [comment]
@Sathish787 it seems to only work find on version 11 of Angular and up. When I upgraded our project from v9 to the latest this plugin worked fine.

**Comment by Sathish787** [comment]
> @Sathish787 it seems to only work find on version 11 of Angular and up. When I upgraded our project from v9 to the latest this plugin worked fine.

Thanks azaeng04.

**Comment by yjaaidi** [comment]
Hi! Thank you for raising the issue and for the investigation.
We are focusing on Angular 11 and up right now.
