### ISSUE TITLE
Angular component is not loading and displays error "Type DynamicModule does not have 'ɵmod' property." in both Angular 11 and Angular 12 application

### ISSUE THREAD

**Issue by Sathish787** [jscutlery/test-utils#55]
Followed instructions as in @jscutlery/cypress-angular - 
https://github.com/jscutlery/test-utils/tree/main/packages/cypress-angular

ng add @jscutlery/cypress-angular
ng g @jscutlery/cypress-angular:setup-ct --project cypress-angular

It did all setup required to execute test. 

then, 
npx cypress open-ct  - it was throwing an error - 
`Error: Error: ENOENT: no such file or directory, lstat 'C:/C/Users/smunirathinam/cyp12-angular/tsconfig.cypress.json'`

I see path is not properly parsed. It should not have "C:/C/" in the path instead "C:/Users"

As a temporary fix, I updated tsConfig path in Index.ts file in cypress directory. Then it started to launch Cypress component Test runner (npx cypress open-ct -b electron)

```
import { startAngularDevServer } from '@jscutlery/cypress-angular';


module.exports = (on: any, config: any) => {
  on('dev-server:start', (options: any) =>
    startAngularDevServer({ options, tsConfig: "/Users/smunirathinam/cyp12-angular/tsconfig.cypress.json" })
  );
  return config;
};
```
When I tried to run sample.cy-spec.ts file in test runner, it displays error as in the screenshot
![angular_cypress](https://user-images.githubusercontent.com/22374311/118543031-c3b2a280-b721-11eb-8cb9-7561c004866b.jpg)

Package.json
```
{
  "name": "cyp12-angular",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "~12.0.0",
    "@angular/forms": "~12.0.0",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@jscutlery/cypress-angular": "^0.3.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.0",
    "@angular/cli": "~12.0.0",
    "@angular/compiler-cli": "~12.0.0",
    "@jscutlery/cypress-mount": "^0.9.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "cypress": "^7.3.0",
    "jasmine-core": "~3.7.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "typescript": "~4.2.3"
  }
}

```

app.module.ts
```

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent,
    
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
    
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by edbzn** [comment]
Did you try to run ngcc before `yarn ngcc # or npm run ngcc` ?

**Comment by Sathish787** [comment]
@edbzn Thank you so much. 
Adding "postinstall": "ngcc" in script section of package.json and running npm run postinstall solved 
"Type DynamicModule does not have 'ɵmod' property." issue.

**Comment by yjaaidi** [comment]
@Sathish787 perfect!
How about the tsconfig path? Do you still have to override it after updating?
Thanks

**Comment by rkrisztian** [comment]
My `package.json` now looks like this (not showing the whole file):

```json
{
	"scripts:" {
		"cypress:open-ct": "ngcc && cypress open-ct",
		"cypress:run-ct": "ngcc && cypress run-ct"
	}
}
```

This works, but shouldn't ngcc be executed by Cypress as it compiles the app sources?

**Comment by edbzn** [comment]
> This works, but shouldn't ngcc be executed by Cypress as it compiles the app sources?

@rkrisztian True, the AngularWebpackPlugin must internally run ngcc, it's maybe due to our actual Webpack configuration. I will try a fix.

**Comment by edbzn** [comment]
Close as it's fixed.

**Comment by Timeout-Timo** [comment]
I am not sure if it's fixed. I'm getting this error with Angular 12.2.0 again...

```cypress_runner.js:190379 Error: Type DynamicModule does not have 'ɵmod' property.
    at getNgModuleDef (http://localhost:36341/__cypress/src/spec-1.js:40378:15)
    at recurse (http://localhost:36341/__cypress/src/spec-1.js:64524:21)
    at recurse (http://localhost:36341/__cypress/src/spec-1.js:64535:17)
    at registerNgModuleType (http://localhost:36341/__cypress/src/spec-1.js:64520:5)
    at new NgModuleFactory$1 (http://localhost:36341/__cypress/src/spec-1.js:64634:13)
    at compileNgModuleFactory__POST_R3__ (http://localhost:36341/__cypress/src/spec-1.js:68333:27)
    at PlatformRef.bootstrapModule (http://localhost:36341/__cypress/src/spec-1.js:68583:16)
    at http://localhost:36341/__cypress/src/spec-1.js:77038:27
    at Generator.next (<anonymous>)
    at http://localhost:36341/__cypress/src/spec-1.js:79516:71
From previous event:
    at Context.thenFn (http://localhost:36341/__cypress/runner/cypress_runner.js:154860:23)
    at Context.then (http://localhost:36341/__cypress/runner/cypress_runner.js:155299:21)
    at Context.<anonymous> (http://localhost:36341/__cypress/runner/cypress_runner.js:170424:21)
    at http://localhost:36341/__cypress/runner/cypress_runner.js:169832:15
From previous event:
    at runCommand (http://localhost:36341/__cypress/runner/cypress_runner.js:169811:8)
    at next (http://localhost:36341/__cypress/runner/cypress_runner.js:169957:14)
From previous event:
    at http://localhost:36341/__cypress/runner/cypress_runner.js:169998:37
From previous event:
    at run (http://localhost:36341/__cypress/runner/cypress_runner.js:169991:21)
    at $Cy.cy.<computed> [as then] (http://localhost:36341/__cypress/runner/cypress_runner.js:170464:11)
    at mount (http://localhost:36341/__cypress/src/spec-1.js:76981:15)
    at Context.<anonymous> (http://localhost:36341/__cypress/src/spec-1.js:79399:80)
    at ZoneDelegate.push.9140.ZoneDelegate.invoke (http://localhost:36341/__cypress/src/628.js:4128:30)
    at ProxyZoneSpec.push.3775.ProxyZoneSpec.onInvoke (http://localhost:36341/__cypress/src/628.js:1821:43)
    at ZoneDelegate.push.9140.ZoneDelegate.invoke (http://localhost:36341/__cypress/src/628.js:4127:56)
    at Zone.push.9140.Zone.run (http://localhost:36341/__cypress/src/628.js:3888:47)
    at Context.<anonymous> (http://localhost:36341/__cypress/src/628.js:2602:37)
    at Context.runnable.fn (http://localhost:36341/__cypress/runner/cypress_runner.js:170688:21)
    at callFn (http://localhost:36341/__cypress/runner/cypress_runner.js:126446:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:36341/__cypress/runner/cypress_runner.js:126433:7)
    at http://localhost:36341/__cypress/runner/cypress_runner.js:176693:28
From previous event:
    at Object.onRunnableRun (http://localhost:36341/__cypress/runner/cypress_runner.js:176681:17)
    at $Cypress.action (http://localhost:36341/__cypress/runner/cypress_runner.js:166772:28)
    at Test.Runnable.run (http://localhost:36341/__cypress/runner/cypress_runner.js:174823:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:36341/__cypress/runner/cypress_runner.js:127105:10)
    at http://localhost:36341/__cypress/src/628.js:2654:37
    at ZoneDelegate.push.9140.ZoneDelegate.invokeTask (http://localhost:36341/__cypress/src/628.js:4162:35)
    at Zone.push.9140.Zone.runTask (http://localhost:36341/__cypress/src/628.js:3933:51)
    at drainMicroTaskQueue (http://localhost:36341/__cypress/src/628.js:4348:39)
logError @ cypress_runner.js:190379```

**Comment by edbzn** [comment]
@Timeout-Timo did you ran ngcc manually? We have not yet implemented the fix for automatically triggering it.

**Comment by Timeout-Timo** [comment]
Yes, I did. I also set ngcc in postinstall of my package.json

**Comment by wshager** [comment]
Ping, this is still an issue.
